const REGEX_EMPTY = /\S+/
const REGEX_CONTACT = /^([0-9]{10})+$/
const REGEX_PIN_CODE = /^([0-9]{6})+$/
const REGEX_EMAIL = /^[\w.+]+@\w+(\.\w{2,3})+$/
const REGEX_NUMBER = /^[0-9]+$/
const REGEX_NUMBER_GREATER_THAN_ZERO = /^[1-9][0-9]*$/
const REGEX_REGISTRATION_NO = /^[A-Z0-9]*$/
const PAGINATION_TOTAL_ENTRIES_PER_PAGE = 5

const USER_ROLE_PERMISSIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
}

const ADMIN_USER_GROUP = 'ADMIN'
const ADMIN_USER_ROLE = 'ADMIN'

const COUNTRIES = [
  { key: 'India', value: 'India' },
  { key: 'United Kingdom', value: 'United Kingdom' },
  { key: 'United States', value: 'United States' },
  { key: 'Australia', value: 'Australia' },
  { key: 'China', value: 'China' },
  { key: 'Canada', value: 'Canada' },
  { key: 'Afghanistan', value: 'Afghanistan' },
  { key: 'Albania', value: 'Albania' },
  { key: 'Algeria', value: 'Algeria' },
  { key: 'Andorra', value: 'Andorra' },
  { key: 'Angola', value: 'Angola' },
  { key: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { key: 'Argentina', value: 'Argentina' },
  { key: 'Armenia', value: 'Armenia' },
  { key: 'Austria', value: 'Austria' },
  { key: 'Azerbaijan', value: 'Azerbaijan' },
  { key: 'Bahamas', value: 'Bahamas' },
  { key: 'Bahrain', value: 'Bahrain' },
  { key: 'Bangladesh', value: 'Bangladesh' },
  { key: 'Barbados', value: 'Barbados' },
  { key: 'Belarus', value: 'Belarus' },
  { key: 'Belgium', value: 'Belgium' },
  { key: 'Belize', value: 'Belize' },
  { key: 'Benin', value: 'Benin' },
  { key: 'Bhutan', value: 'Bhutan' },
  { key: 'Bolivia', value: 'Bolivia' },
  { key: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { key: 'Botswana', value: 'Botswana' },
  { key: 'Brazil', value: 'Brazil' },
  { key: 'Brunei', value: 'Brunei' },
  { key: 'Bulgaria', value: 'Bulgaria' },
  { key: 'Burkina Faso', value: 'Burkina Faso' },
  { key: 'Burundi', value: 'Burundi' },
  { key: 'Cabo Verde', value: 'Cabo Verde' },
  { key: 'Cambodia', value: 'Cambodia' },
  { key: 'Cameroon', value: 'Cameroon' },
  { key: 'Central African Republic', value: 'Central African Republic' },
  { key: 'Chad', value: 'Chad' },
  { key: 'Chile', value: 'Chile' },
  { key: 'Colombia', value: 'Colombia' },
  { key: 'Comoros', value: 'Comoros' },
  { key: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)' },
  { key: 'Congo (Democratic Republic)', value: 'Congo (Democratic Republic)' },
  { key: 'Costa Rica', value: 'Costa Rica' },
  { key: 'Croatia', value: 'Croatia' },
  { key: 'Croatia', value: 'Croatia' },
  { key: 'Cuba', value: 'Cuba' },
  { key: 'Cyprus', value: 'Cyprus' },
  { key: 'Czech Republic', value: 'Czech Republic' },
  { key: 'Czechia', value: 'Czechia' },
  { key: 'Denmark', value: 'Denmark' },
  { key: 'Djibouti', value: 'Djibouti' },
  { key: 'Dominica', value: 'Dominica' },
  { key: 'Dominican Republic', value: 'Dominican Republic' },
  { key: 'Ecuador', value: 'Ecuador' },
  { key: 'Egypt', value: 'Egypt' },
  { key: 'El Salvador', value: 'El Salvador' },
  { key: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { key: 'Eritrea', value: 'Eritrea' },
  { key: 'Estonia', value: 'Estonia' },
  { key: 'Eswatini', value: 'Eswatini' },
  { key: 'Ethiopia', value: 'Ethiopia' },
  { key: 'Finland', value: 'Finland' },
  { key: 'France', value: 'France' },
  { key: 'Germany', value: 'Germany' },
  { key: 'Greece', value: 'Greece' },
  { key: 'Hungary', value: 'Hungary' },
  { key: 'Ireland', value: 'Ireland' },
  { key: 'Italy', value: 'Italy' },
  { key: 'Japan', value: 'Japan' },
  { key: 'Mexico', value: 'Mexico' },
  { key: 'Netherlands', value: 'Netherlands' },
  { key: 'New Zealand', value: 'New Zealand' },
  { key: 'Norway', value: 'Norway' },
  { key: 'Poland', value: 'Poland' },
  { key: 'Portugal', value: 'Portugal' },
  { key: 'Romania', value: 'Romania' },
  { key: 'Russia', value: 'Russia' },
  { key: 'Saudi Arabia', value: 'Saudi Arabia' },
  { key: 'Serbia', value: 'Serbia' },
  { key: 'Slovakia', value: 'Slovakia' },
  { key: 'Slovenia', value: 'Slovenia' },
  { key: 'South Africa', value: 'South Africa' },
  { key: 'South Korea', value: 'South Korea' },
  { key: 'Spain', value: 'Spain' },
  { key: 'Sweden', value: 'Sweden' },
  { key: 'Switzerland', value: 'Switzerland' },
  { key: 'Turkey', value: 'Turkey' },
  { key: 'Ukraine', value: 'Ukraine' },
]

const STATES: Record<string, Array<{ key: string; value: string }>> = {
  India: [
    { key: 'Andhra Pradesh', value: 'Andhra Pradesh' },
    { key: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
    { key: 'Assam', value: 'Assam' },
    { key: 'Bihar', value: 'Bihar' },
    { key: 'Chhattisgarh', value: 'Chhattisgarh' },
    { key: 'Goa', value: 'Goa' },
    { key: 'Gujarat', value: 'Gujarat' },
    { key: 'Haryana', value: 'Haryana' },
    { key: 'Himachal Pradesh', value: 'Himachal Pradesh' },
    { key: 'Jharkhand', value: 'Jharkhand' },
    { key: 'Karnataka', value: 'Karnataka' },
    { key: 'Kerala', value: 'Kerala' },
    { key: 'Madhya Pradesh', value: 'Madhya Pradesh' },
    { key: 'Maharashtra', value: 'Maharashtra' },
    { key: 'Manipur', value: 'Manipur' },
    { key: 'Meghalaya', value: 'Meghalaya' },
    { key: 'Mizoram', value: 'Mizoram' },
    { key: 'Nagaland', value: 'Nagaland' },
    { key: 'Odisha', value: 'Odisha' },
    { key: 'Punjab', value: 'Punjab' },
    { key: 'Rajasthan', value: 'Rajasthan' },
    { key: 'Sikkim', value: 'Sikkim' },
    { key: 'Tamil Nadu', value: 'Tamil Nadu' },
    { key: 'Telangana', value: 'Telangana' },
    { key: 'Tripura', value: 'Tripura' },
    { key: 'Uttar Pradesh', value: 'Uttar Pradesh' },
    { key: 'Uttarakhand', value: 'Uttarakhand' },
    { key: 'West Bengal', value: 'West Bengal' },
    { key: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands' },
    { key: 'Chandigarh', value: 'Chandigarh' },
    { key: 'Dadra and Nagar Haveli and Daman and Diu', value: 'Dadra and Nagar Haveli and Daman and Diu' },
    { key: 'Delhi', value: 'Delhi' },
    { key: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
    { key: 'Ladakh', value: 'Ladakh' },
    { key: 'Lakshadweep', value: 'Lakshadweep' },
    { key: 'Puducherry', value: 'Puducherry' },
  ],
  'United States': [
    { key: 'Alabama', value: 'Alabama' },
    { key: 'Alaska', value: 'Alaska' },
    { key: 'Arizona', value: 'Arizona' },
    { key: 'Arkansas', value: 'Arkansas' },
    { key: 'California', value: 'California' },
    { key: 'Colorado', value: 'Colorado' },
    { key: 'Connecticut', value: 'Connecticut' },
    { key: 'Delaware', value: 'Delaware' },
    { key: 'Florida', value: 'Florida' },
    { key: 'Georgia', value: 'Georgia' },
    { key: 'Hawaii', value: 'Hawaii' },
    { key: 'Idaho', value: 'Idaho' },
    { key: 'Illinois', value: 'Illinois' },
    { key: 'Indiana', value: 'Indiana' },
    { key: 'Iowa', value: 'Iowa' },
    { key: 'Kansas', value: 'Kansas' },
    { key: 'Kentucky', value: 'Kentucky' },
    { key: 'Louisiana', value: 'Louisiana' },
    { key: 'Maine', value: 'Maine' },
    { key: 'Maryland', value: 'Maryland' },
    { key: 'Massachusetts', value: 'Massachusetts' },
    { key: 'Michigan', value: 'Michigan' },
    { key: 'Minnesota', value: 'Minnesota' },
    { key: 'Mississippi', value: 'Mississippi' },
    { key: 'Missouri', value: 'Missouri' },
    { key: 'Montana', value: 'Montana' },
    { key: 'Nebraska', value: 'Nebraska' },
    { key: 'Nevada', value: 'Nevada' },
    { key: 'New Hampshire', value: 'New Hampshire' },
    { key: 'New Jersey', value: 'New Jersey' },
    { key: 'New Mexico', value: 'New Mexico' },
    { key: 'New York', value: 'New York' },
    { key: 'North Carolina', value: 'North Carolina' },
    { key: 'North Dakota', value: 'North Dakota' },
    { key: 'Ohio', value: 'Ohio' },
    { key: 'Oklahoma', value: 'Oklahoma' },
    { key: 'Oregon', value: 'Oregon' },
    { key: 'Pennsylvania', value: 'Pennsylvania' },
    { key: 'Rhode Island', value: 'Rhode Island' },
    { key: 'South Carolina', value: 'South Carolina' },
    { key: 'South Dakota', value: 'South Dakota' },
    { key: 'Tennessee', value: 'Tennessee' },
    { key: 'Texas', value: 'Texas' },
    { key: 'Utah', value: 'Utah' },
    { key: 'Vermont', value: 'Vermont' },
    { key: 'Virginia', value: 'Virginia' },
    { key: 'Washington', value: 'Washington' },
    { key: 'West Virginia', value: 'West Virginia' },
    { key: 'Wisconsin', value: 'Wisconsin' },
    { key: 'Wyoming', value: 'Wyoming' },
  ],
  Canada: [
    { key: 'Alberta', value: 'Alberta' },
    { key: 'British Columbia', value: 'British Columbia' },
    { key: 'Manitoba', value: 'Manitoba' },
    { key: 'New Brunswick', value: 'New Brunswick' },
    { key: 'Newfoundland and Labrador', value: 'Newfoundland and Labrador' },
    { key: 'Nova Scotia', value: 'Nova Scotia' },
    { key: 'Ontario', value: 'Ontario' },
    { key: 'Prince Edward Island', value: 'Prince Edward Island' },
    { key: 'Quebec', value: 'Quebec' },
    { key: 'Saskatchewan', value: 'Saskatchewan' },
    { key: 'Northwest Territories', value: 'Northwest Territories' },
    { key: 'Nunavut', value: 'Nunavut' },
    { key: 'Yukon', value: 'Yukon' },
  ],
  Australia: [
    { key: 'Australian Capital Territory', value: 'Australian Capital Territory' },
    { key: 'New South Wales', value: 'New South Wales' },
    { key: 'Northern Territory', value: 'Northern Territory' },
    { key: 'Queensland', value: 'Queensland' },
    { key: 'South Australia', value: 'South Australia' },
    { key: 'Tasmania', value: 'Tasmania' },
    { key: 'Victoria', value: 'Victoria' },
    { key: 'Western Australia', value: 'Western Australia' },
  ],
  'United Kingdom': [
    { key: 'England', value: 'England' },
    { key: 'Scotland', value: 'Scotland' },
    { key: 'Wales', value: 'Wales' },
    { key: 'Northern Ireland', value: 'Northern Ireland' },
  ],
  China: [
    { key: 'Anhui', value: 'Anhui' },
    { key: 'Beijing', value: 'Beijing' },
    { key: 'Chongqing', value: 'Chongqing' },
    { key: 'Fujian', value: 'Fujian' },
    { key: 'Gansu', value: 'Gansu' },
    { key: 'Guangdong', value: 'Guangdong' },
    { key: 'Guangxi', value: 'Guangxi' },
    { key: 'Guizhou', value: 'Guizhou' },
    { key: 'Hainan', value: 'Hainan' },
    { key: 'Hebei', value: 'Hebei' },
    { key: 'Heilongjiang', value: 'Heilongjiang' },
    { key: 'Henan', value: 'Henan' },
    { key: 'Hong Kong', value: 'Hong Kong' },
    { key: 'Hubei', value: 'Hubei' },
    { key: 'Hunan', value: 'Hunan' },
    { key: 'Inner Mongolia', value: 'Inner Mongolia' },
    { key: 'Jiangsu', value: 'Jiangsu' },
    { key: 'Jiangxi', value: 'Jiangxi' },
    { key: 'Jilin', value: 'Jilin' },
    { key: 'Liaoning', value: 'Liaoning' },
    { key: 'Macau', value: 'Macau' },
    { key: 'Ningxia', value: 'Ningxia' },
    { key: 'Qinghai', value: 'Qinghai' },
    { key: 'Shaanxi', value: 'Shaanxi' },
    { key: 'Shandong', value: 'Shandong' },
    { key: 'Shanghai', value: 'Shanghai' },
    { key: 'Shanxi', value: 'Shanxi' },
    { key: 'Sichuan', value: 'Sichuan' },
    { key: 'Tianjin', value: 'Tianjin' },
    { key: 'Tibet', value: 'Tibet' },
    { key: 'Xinjiang', value: 'Xinjiang' },
    { key: 'Yunnan', value: 'Yunnan' },
    { key: 'Zhejiang', value: 'Zhejiang' },
  ],
  Afghanistan: [],
  Albania: [],
  Algeria: [],
  Andorra: [],
  Angola: [],
  'Antigua and Barbuda': [],
  Argentina: [],
  Armenia: [],
  Austria: [],
  Azerbaijan: [],
  Bahamas: [],
  Bahrain: [],
  Bangladesh: [],
  Barbados: [],
  Belarus: [],
  Belgium: [],
  Belize: [],
  Benin: [],
  Bhutan: [],
  Bolivia: [],
  'Bosnia and Herzegovina': [],
  Botswana: [],
  Brazil: [],
  Brunei: [],
  Bulgaria: [],
  'Burkina Faso': [],
  Burundi: [],
  'Cabo Verde': [],
  Cambodia: [],
  Cameroon: [],
  'Central African Republic': [],
  Chad: [],
  Chile: [],
  Colombia: [],
  Comoros: [],
  'Congo (Congo-Brazzaville)': [],
  'Congo (Democratic Republic)': [],
  'Costa Rica': [],
  Croatia: [],
  Cuba: [],
  Cyprus: [],
  'Czech Republic': [],
  Czechia: [],
  Denmark: [],
  Djibouti: [],
  Dominica: [],
  'Dominican Republic': [],
  Ecuador: [],
  Egypt: [],
  'El Salvador': [],
  'Equatorial Guinea': [],
  Eritrea: [],
  Estonia: [],
  Eswatini: [],
  Ethiopia: [],
  Finland: [],
  France: [],
  Germany: [],
  Greece: [],
  Hungary: [],
  Ireland: [],
  Italy: [],
  Japan: [],
  Mexico: [],
  Netherlands: [],
  'New Zealand': [],
  Norway: [],
  Poland: [],
  Portugal: [],
  Romania: [],
  Russia: [],
  'Saudi Arabia': [],
  Serbia: [],
  Slovakia: [],
  Slovenia: [],
  'South Africa': [],
  'South Korea': [],
  Spain: [],
  Sweden: [],
  Switzerland: [],
  Turkey: [],
  Ukraine: [],
}

// For countries without states/provinces, use an empty array or a single entry with the country name.

const COUNTRY_CODES = [
  { key: 'India', value: '+91' },
  { key: 'Afghanistan', value: '+93' },
  { key: 'Albania', value: '+355' },
  { key: 'Algeria', value: '+213' },
  { key: 'Andorra', value: '+376' },
  { key: 'Angola', value: '+244' },
  { key: 'Antigua and Barbuda', value: '+1-268' },
  { key: 'Argentina', value: '+54' },
  { key: 'Armenia', value: '+374' },
  { key: 'Australia', value: '+61' },
  { key: 'Austria', value: '+43' },
  { key: 'Azerbaijan', value: '+994' },
  { key: 'Bahamas', value: '+1-242' },
  { key: 'Bahrain', value: '+973' },
  { key: 'Bangladesh', value: '+880' },
  { key: 'Barbados', value: '+1-246' },
  { key: 'Belarus', value: '+375' },
  { key: 'Belgium', value: '+32' },
  { key: 'Belize', value: '+501' },
  { key: 'Benin', value: '+229' },
  { key: 'Bhutan', value: '+975' },
  { key: 'Bolivia', value: '+591' },
  { key: 'Bosnia and Herzegovina', value: '+387' },
  { key: 'Botswana', value: '+267' },
  { key: 'Brazil', value: '+55' },
  { key: 'Brunei', value: '+673' },
  { key: 'Bulgaria', value: '+359' },
  { key: 'Burkina Faso', value: '+226' },
  { key: 'Burundi', value: '+257' },
  { key: 'Cabo Verde', value: '+238' },
  { key: 'Cambodia', value: '+855' },
  { key: 'Cameroon', value: '+237' },
  { key: 'Canada', value: '+1' },
  { key: 'Central African Republic', value: '+236' },
  { key: 'Chad', value: '+235' },
  { key: 'Chile', value: '+56' },
  { key: 'China', value: '+86' },
  { key: 'Colombia', value: '+57' },
  { key: 'Comoros', value: '+269' },
  { key: 'Congo (Congo-Brazzaville)', value: '+242' },
  { key: 'Congo (Democratic Republic)', value: '+243' },
  { key: 'Costa Rica', value: '+506' },
  { key: 'Croatia', value: '+385' },
  { key: 'Croatia', value: '+385' },
  { key: 'Cuba', value: '+53' },
  { key: 'Cyprus', value: '+357' },
  { key: 'Czech Republic', value: '+420' },
  { key: 'Czechia', value: '+420' },
  { key: 'Denmark', value: '+45' },
  { key: 'Djibouti', value: '+253' },
  { key: 'Dominica', value: '+1-767' },
  { key: 'Dominican Republic', value: '+1-809' },
  { key: 'Ecuador', value: '+593' },
  { key: 'Egypt', value: '+20' },
  { key: 'El Salvador', value: '+503' },
  { key: 'Equatorial Guinea', value: '+240' },
  { key: 'Eritrea', value: '+291' },
  { key: 'Estonia', value: '+372' },
  { key: 'Eswatini', value: '+268' },
  { key: 'Ethiopia', value: '+251' },
  { key: 'Finland', value: '+358' },
  { key: 'France', value: '+33' },
  { key: 'Germany', value: '+49' },
  { key: 'Greece', value: '+30' },
  { key: 'Hungary', value: '+36' },
  { key: 'Ireland', value: '+353' },
  { key: 'Italy', value: '+39' },
  { key: 'Japan', value: '+81' },
  { key: 'Mexico', value: '+52' },
  { key: 'Netherlands', value: '+31' },
  { key: 'New Zealand', value: '+64' },
  { key: 'Norway', value: '+47' },
  { key: 'Poland', value: '+48' },
  { key: 'Portugal', value: '+351' },
  { key: 'Romania', value: '+40' },
  { key: 'Russia', value: '+7' },
  { key: 'Saudi Arabia', value: '+966' },
  { key: 'Serbia', value: '+381' },
  { key: 'Slovakia', value: '+421' },
  { key: 'Slovenia', value: '+386' },
  { key: 'South Africa', value: '+27' },
  { key: 'South Korea', value: '+82' },
  { key: 'Spain', value: '+34' },
  { key: 'Sweden', value: '+46' },
  { key: 'Switzerland', value: '+41' },
  { key: 'Turkey', value: '+90' },
  { key: 'Ukraine', value: '+380' },
  { key: 'United Kingdom', value: '+44' },
  { key: 'United States', value: '+1' },
]

enum CONFIGURED_INPUT_TYPES {
  SELECT = 'SELECT',
  RADIO = 'RADIO',
  CHECKBOX = 'CHECKBOX',
}

export {
  REGEX_EMPTY,
  REGEX_CONTACT,
  REGEX_PIN_CODE,
  REGEX_EMAIL,
  REGEX_NUMBER,
  REGEX_NUMBER_GREATER_THAN_ZERO,
  REGEX_REGISTRATION_NO,
  USER_ROLE_PERMISSIONS,
  ADMIN_USER_GROUP,
  ADMIN_USER_ROLE,
  COUNTRIES,
  COUNTRY_CODES,
  CONFIGURED_INPUT_TYPES,
  STATES,
  PAGINATION_TOTAL_ENTRIES_PER_PAGE,
}
